homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
    - type: homeassistant
  packages: !include_dir_named components/packages
  customize: !include_dir_merge_named customize