homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: homeassistant
  packages: !include_dir_named components/packages
  customize: !include customize.yaml
