type: custom:mod-card
card_mod:
  style:
    auto-entities:
      hui-grid-card$: |
        h1 {
          padding: 8px !IMPORTANT;
          font-weight: bold !IMPORTANT;
        }
card:
  type: "custom:auto-entities"
  show_empty: false
  filter:
    include: |
      [[[
        this.entities = []
        if ("yatbi" in entity.attributes){
          if ("entities" in entity.attributes.yatbi){
            for (let selected_entity in entity.attributes.yatbi.entities) {
              let selected_entity_id = entity.attributes.yatbi.entities[selected_entity]
              if (typeof(selected_entity_id) == "object") {
                selected_entity_id = selected_entity_id["entity"]
              }
              switch (selected_entity_id.startsWith('input_boolean.automation')) {
                case true:
                  const object =
                    {
                      "entity_id": selected_entity_id,
                      "options":
                        {
                          "type": "custom:button-card",
                          "template": "popup_auto_hold"
                        }
                    }
                  this.entities.push(object)
                  break
              }
            }
          }
        }
        return this.entities
      ]]]
  card:
    type: grid
    title: Automations
  card_param: cards
