type: custom:decluttering-card
template: popup
variables:
- entity: '[[[return `${entity.entity_id}`]]]'
- name: '[[[return `${entity.attributes.friendly_name}`]]]'
- cards:
  - !include header.yaml

  - type: custom:decluttering-card
    template: '[[[return `${entity.entity_id}`]]]'

  - !include footer.yaml