- platform: thermal_comfort
  sensors:
    climate_terrarium_amduat:
      friendly_name: Terrarium Amduat
      temperature_sensor: sensor.climate_temperature_amduat
      humidity_sensor: sensor.climate_humidity_amduat
    climate_terrarium_ghost:
      friendly_name: Terrarium Ghost
      temperature_sensor: sensor.climate_temperature_ghost
      humidity_sensor: sensor.climate_humidity_ghost
    climate_terrarium_naga:
      friendly_name: Terrarium Naga
      temperature_sensor: sensor.climate_temperature_naga
      humidity_sensor: sensor.climate_humidity_naga
    climate_living_room:
      friendly_name: Climate Living Room
      temperature_sensor: sensor.climate_temperature_living_room
      humidity_sensor: sensor.climate_humidity_living_room